name: CI - Unit Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged # Optional, aber kann helfen, Berechtigungsprobleme mit Docker zu vermeiden

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Start Docker Service
        run: |
          sudo service docker start
          docker --version

      - name: Restore Dependencies
        run: dotnet restore NuvellAPI.sln

      - name: Build Solution
        run: dotnet build NuvellAPI.sln --configuration Release --no-restore

      - name: Run Integration Tests
        run: dotnet test tests/NuvellApi.IntegrationTests/ --configuration Release --no-build --logger trx --results-directory TestResults

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults
