name: CI - Unit Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up .NET SDK
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      # Step 3: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 4: Restore Dependencies
      - name: Restore Dependencies
        run: dotnet restore NuvellAPI.sln

      # Step 5: Build Solution
      - name: Build Solution
        run: dotnet build NuvellAPI.sln --configuration Release --no-restore

      # Step 6: Run Integration Tests (with TestContainers)
      - name: Run Integration Tests
        run: |
          dotnet test tests/NuvellApi.IntegrationTests/ --configuration Release --no-build --logger trx --results-directory TestResults

      # Step 7: Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults

